### PR TITLE
Add OCL3.0 support

### PR DESCRIPTION
**Pull request by haonanya**
Signed-off-by: Haonan Yang <haonan.yang@intel.com>

### CODE REVIEW

**Review by hewj03 — APPROVED** [review]
is this also needed for 100/110 branches?

**Comment by haonanya** [comment]
> is this also needed for 100/110 branches?

There are OCL 3.0 support on 100/110 branches already.

**Comment by hewj03** [comment]
> > is this also needed for 100/110 branches?
> 
> There are OCL 3.0 support on 100/110 branches already.

I didn't find __opencl_c_fp64 in 100/110 options

**Comment by haonanya** [comment]
> > > is this also needed for 100/110 branches?
> > 
> > 
> > There are OCL 3.0 support on 100/110 branches already.
> 
> I didn't find __opencl_c_fp64 in 100/110 options

The OCL 3.0 support patch is backported from https://github.com/llvm/llvm-project/blob/main/clang/docs/OpenCLSupport.rst#opencl-c-30-implementation-status, maybe patches on 100/110 have gap with current llvmorg. And PCH patch on 110/120 is enabled recently without CI check, I will have a check if __opencl_c_fp64 is needed on CMake .

**Comment by hewj03** [comment]
> > > > is this also needed for 100/110 branches?
> > > 
> > > 
> > > There are OCL 3.0 support on 100/110 branches already.
> > 
> > 
> > I didn't find __opencl_c_fp64 in 100/110 options
> 
> The OCL 3.0 support patch is backported from https://github.com/llvm/llvm-project/blob/main/clang/docs/OpenCLSupport.rst#opencl-c-30-implementation-status, maybe patches on 100/110 have gap with current llvmorg. And PCH patch on 110/120 is enabled recently without CI check, I will have a check if __opencl_c_fp64 is needed on CMake .

I see, thanks

**Comment by haonanya** [comment]
> > > > > is this also needed for 100/110 branches?
> > > > 
> > > > 
> > > > There are OCL 3.0 support on 100/110 branches already.
> > > 
> > > 
> > > I didn't find __opencl_c_fp64 in 100/110 options
> > 
> > 
> > The OCL 3.0 support patch is backported from https://github.com/llvm/llvm-project/blob/main/clang/docs/OpenCLSupport.rst#opencl-c-30-implementation-status, maybe patches on 100/110 have gap with current llvmorg. And PCH patch on 110/120 is enabled recently without CI check, I will have a check if __opencl_c_fp64 is needed on CMake .
> 
> I see, thanks

It seems that cl_khr_fp64 and __opencl_c_fp64 are defined simultaneously on 100/110 according to https://github.com/intel/opencl-clang/blob/ocl-open-100/patches/clang/0001-OpenCL-3.0-support.patch#L892,L897 and https://github.com/intel/opencl-clang/blob/ocl-open-110/patches/clang/0001-OpenCL-3.0-support.patch#L887,891. But for llvmorg, it need user to make sure  cl_khr_fp64 and __opencl_c_fp64 are set to same values according to https://reviews.llvm.org/D96524.
Maybe we don't need the CMake change for 100/110 and currently there are no build errors on 100/110.

**Comment by hewj03** [comment]
> > > > > > is this also needed for 100/110 branches?
> > > > > 
> > > > > 
> > > > > There are OCL 3.0 support on 100/110 branches already.
> > > > 
> > > > 
> > > > I didn't find __opencl_c_fp64 in 100/110 options
> > > 
> > > 
> > > The OCL 3.0 support patch is backported from https://github.com/llvm/llvm-project/blob/main/clang/docs/OpenCLSupport.rst#opencl-c-30-implementation-status, maybe patches on 100/110 have gap with current llvmorg. And PCH patch on 110/120 is enabled recently without CI check, I will have a check if __opencl_c_fp64 is needed on CMake .
> > 
> > 
> > I see, thanks
> 
> It seems that cl_khr_fp64 and __opencl_c_fp64 are defined simultaneously on 100/110 according to https://github.com/intel/opencl-clang/blob/ocl-open-100/patches/clang/0001-OpenCL-3.0-support.patch#L892,L897 and https://github.com/intel/opencl-clang/blob/ocl-open-110/patches/clang/0001-OpenCL-3.0-support.patch#L887,891. But for llvmorg, it need user to make sure cl_khr_fp64 and __opencl_c_fp64 are set to same values according to https://reviews.llvm.org/D96524. Maybe we don't need the CMake change for 100/110 and currently there are no build errors on 100/110.

I agree. LGTM

**Pull request merged**
