### PR TITLE
Update OpenCL C 3.0 support patch

### PR DESCRIPTION
**Pull request by azabazno**

### CODE REVIEW

**Comment by hewj03** [comment]
see https://github.com/intel/opencl-clang/pull/176#issuecomment-698040927

**Comment by azabazno** [comment]
@hewj03 thanks for comments! I see there was a change in patching of monorepo. So can this be merged too?

**Comment by hewj03** [comment]
yes this can be merged. I've verified locally.

**Comment by azabazno** [comment]
Thanks!

**Review by fzou1 — APPROVED** [review]
LGTM.

**Review by fzou1 — APPROVED** [review]

**Comment by fzou1** [comment]
LGTM. I assumed @azabazno had verified the functionality by himself. Thanks.

**Pull request merged**
