### PR TITLE
GitHub action improvements

### PR DESCRIPTION
**Pull request by pszymich**
* Run verification build for all ocl-open-* releases branches weekly,
* A separate workflow for running verification on demand,
* Much improved on push/pull_request verification workflow that parses
destination branch to get correct dependencies,
* Remove deprecated workflow file.

### CODE REVIEW

**Comment by mnaczk** [comment]
Pull requests for branches older than ocl-open-80 will not be working because SPIRV-LLVM-Translators do not have branches older than ocl-open-80. 
List of active  SPIRV-LLVM-Translators branches: https://github.com/KhronosGroup/SPIRV-LLVM-Translator/branches/active

**Review by hewj03 — APPROVED** [review]
LGTM

**Comment by pszymich** [comment]
Thanks @hewj03, can we merge this, and related PRs?

**Comment by hewj03** [comment]
@pszymich done, thanks.

**Pull request merged**
