### PR TITLE
Add patch to resolve overloads issue with generic AS

### PR DESCRIPTION
**Pull request by azabazno**

### CODE REVIEW

**Comment by fzou1** [comment]
LGTM. I'll merge it firstly.
@cdai2 , @hewj03 , @woshiyifei , please review it. Thanks.

**Comment by azabazno** [comment]
Reproduction:
8.0: https://godbolt.org/z/7acq69
9.0: https://godbolt.org/z/eGo4eM

**Comment by hewj03** [comment]
LGTM

**Comment by woshiyifei** [comment]
LGTM +1

**Pull request merged**
