### PR TITLE
Enable precompiled headers

### PR DESCRIPTION
**Pull request by haonanya**
Signed-off-by: haonanya <haonan.yang@intel.com>

### CODE REVIEW

**Comment by hewj03** [comment]
do you need this patch for all branches including master?

**Comment by haonanya** [comment]
> do you need this patch for all branches including master?

Yes, according to Lukasz, it should be from branch ocl-open-100 to master.

**Comment by hewj03** [comment]
@haonanya do you need to update this patch, or is it ready to land?

**Comment by haonanya** [comment]
> @haonanya do you need to update this patch, or is it ready to land?

It is ready to land, thanks.

**Review by hewj03 — APPROVED** [review]
sorry for the late response

**Pull request merged**
