### PR TITLE
Correction for CLANG_BASE_REVISION setup

### PR DESCRIPTION
**Pull request by lwesiers**

### CODE REVIEW

**Comment by bader** [comment]
@lwesiers, please, fix CI failure:

```
/home/travis/build/intel/opencl-clang/common_clang.cpp:329:19: error: ‘class SPIRV::TranslatorOpts’ has no member named ‘setMemToRegEnabled’
         SPIRVOpts.setMemToRegEnabled(true);
                   ^
```

**Comment by AlexeySachkov** [comment]
> @lwesiers, please, fix CI failure:
> 
> ```
> /home/travis/build/intel/opencl-clang/common_clang.cpp:329:19: error: ‘class SPIRV::TranslatorOpts’ has no member named ‘setMemToRegEnabled’
>          SPIRVOpts.setMemToRegEnabled(true);
>                    ^
> ```

This failure cannot be fixed in this repo, we need to re-upload new pre-built binaries for the translator

**Comment by bader** [comment]
What is the point in having CI, which reports failures we can't fix?

**Comment by bader** [comment]
I can merge assuming that you tested this change and will be responsible for handling regressions/issues related to this change.

We can discuss CI system improvements separately.

@AlexeySachkov, @lwesiers, are you okay with this?

**Pull request merged**
