### PR TITLE
[ocl-open-100] Release locks for compilation tasks for improving build time 

### PR DESCRIPTION
**Pull request by yeonbok**
Unlock the compilation tasks  (IR build  & writeSPIRV), which was the bottleneck of the parallel build performance.

### CODE REVIEW

**Comment by yeonbok** [comment]
@hewj03  @haonanya  @cdai2  Hi, could you please review this?

**Review by hewj03 — APPROVED** [review]
LGTM. I have a question, is there any thread safety issue if we just remove compileGuard?

**Comment by yeonbok** [comment]
> LGTM. I have a question, is there any thread safety issue if we just remove compileGuard?

If we just remove the guarding, seems there is thread unsafety within option processing and result updating. 
I think we can fix it with some more code refactoring.

**Comment by hewj03** [comment]
I see, thanks

**Pull request merged**
