### PR TITLE
add 'Visibility' field to Option

### PR DESCRIPTION
**Pull request by wwXing0**
Caused by https://github.com/intel/llvm/commit/dcb6d212fdfb1db60bc5ba1c877897cb5ba0546c

### CODE REVIEW

**Comment by tylanphear** [comment]
Could someone (maybe @haonanya or @hewj03) please review/merge this ASAP? This is breaking the downstream build. Thanks.

**Comment by bader** [comment]
> Can we get this merged first to unblock the build? Thanks.

@jsji, I do not maintain this project anymore, so I'll let @haonanya or @hewj03 to decide.

**Comment by jsji** [comment]
> @jsji, I do not maintain this project anymore, so I'll let @haonanya or @hewj03 to decide.

OK. Thanks.

**Review by hewj03 — APPROVED** [review]
LGTM

**Pull request merged**
