### PR TITLE
Enable compiler generation of CFG security checks

### PR DESCRIPTION
**Pull request by AlexeySotkin**

### CODE REVIEW

**Comment by AlexeySotkin** [comment]
@PawelJurek, please take a look.

**Comment by PawelJurek** [comment]
I'm not sure if it will work as expected, did you verify it? 
It seems that /DYNAMICBASE is a linker option and guard:cf is for both compiler and linker.
Shouldn't we set CMAKE_EXE_LINKER_FLAGS  as well?

**Comment by AlexeySotkin** [comment]
I'll double check.

**Comment by AlexeySotkin** [comment]
I was right @PawelJurek. I have updated the patch

**Pull request merged**
